{{- if .Values.postgres.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cullis-mastio.postgres.fullname" . }}
  labels:
    {{- include "cullis-mastio.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "cullis-mastio.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
