"""
generate_certs.py — Generate the broker CA for Agent Trust Network.

Structure:
  certs/broker-ca.pem          Broker root CA (10 years)
  certs/broker-ca-key.pem      Root CA private key

Fully idempotent: if files already exist they are skipped.

Usage:
  python generate_certs.py                   # default: RSA 4096
  python generate_certs.py --key-type ec     # ECDSA P-256

NOTE: Organization certificates are generated by each company independently
      using join.py, which creates their own CA and agent certs and sends
      a join request to the broker.
"""
import argparse
import datetime
import os
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.x509.oid import NameOID

# ─────────────────────────────────────────────
# Configurazione
# ─────────────────────────────────────────────

CERTS_DIR = Path(__file__).parent / "certs"

NOW = datetime.datetime.now(datetime.timezone.utc)

RESET = "\033[0m"
GREEN = "\033[32m"
YELLOW = "\033[33m"


def _ok(msg: str) -> None:
    print(f"  {GREEN}✓{RESET}  {msg}")


def _skip(msg: str) -> None:
    print(f"  {YELLOW}→{RESET}  {msg} (already exists — skip)")


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

def _gen_key(key_type: str = "rsa", bits: int = 2048):
    """Generate an RSA or EC (P-256) private key."""
    if key_type == "rsa":
        return rsa.generate_private_key(public_exponent=65537, key_size=bits)
    if key_type == "ec":
        return ec.generate_private_key(ec.SECP256R1())
    raise ValueError(f"Unsupported --key-type: {key_type!r} (use 'rsa' or 'ec')")


# Backward-compatible alias — other modules may still import _gen_rsa_key.
def _gen_rsa_key(bits: int) -> rsa.RSAPrivateKey:
    return _gen_key("rsa", bits=bits)


def _save_key(path: Path, key) -> None:
    path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    path.chmod(0o600)  # owner read/write only — protect private key


def _save_cert(path: Path, cert: x509.Certificate) -> None:
    path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))


def _load_key(path: Path) -> rsa.RSAPrivateKey:
    return serialization.load_pem_private_key(path.read_bytes(), password=None)


def _load_cert(path: Path) -> x509.Certificate:
    return x509.load_pem_x509_certificate(path.read_bytes())


def _build_name(*rdns: tuple[x509.ObjectIdentifier, str]) -> x509.Name:
    return x509.Name([x509.NameAttribute(oid, val) for oid, val in rdns])


# ─────────────────────────────────────────────
# Generatori
# ─────────────────────────────────────────────

def gen_broker_ca(key_type: str = "rsa"):
    """Generate (or load) the broker root CA.

    key_type="rsa" → RSA 4096
    key_type="ec"  → ECDSA P-256
    """
    key_path = CERTS_DIR / "broker-ca-key.pem"
    cert_path = CERTS_DIR / "broker-ca.pem"

    if key_path.exists() and cert_path.exists():
        _skip("broker CA")
        return _load_key(key_path), _load_cert(cert_path)

    key = _gen_key(key_type, bits=4096)
    name = _build_name(
        (NameOID.COMMON_NAME, "Agent Trust Network Root CA"),
        (NameOID.ORGANIZATION_NAME, "Agent Trust Network"),
    )
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(NOW)
        .not_valid_after(NOW + datetime.timedelta(days=365 * 10))
        .add_extension(x509.BasicConstraints(ca=True, path_length=1), critical=True)
        .add_extension(
            x509.SubjectKeyIdentifier.from_public_key(key.public_key()),
            critical=False,
        )
        .sign(key, hashes.SHA256())
    )
    _save_key(key_path, key)
    _save_cert(cert_path, cert)
    _ok("broker CA generated")
    return key, cert


def gen_org_ca(
    org_id: str,
    broker_ca_key,
    broker_ca_cert: x509.Certificate,
    key_type: str = "rsa",
):
    """Generate (or load) the org intermediate CA."""
    org_dir = CERTS_DIR / org_id
    org_dir.mkdir(parents=True, exist_ok=True)

    key_path = org_dir / "ca-key.pem"
    cert_path = org_dir / "ca.pem"

    if key_path.exists() and cert_path.exists():
        _skip(f"{org_id} org CA")
        return _load_key(key_path), _load_cert(cert_path)

    key = _gen_key(key_type, bits=2048)
    subject = _build_name(
        (NameOID.COMMON_NAME, f"{org_id} Intermediate CA"),
        (NameOID.ORGANIZATION_NAME, org_id),
    )
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(broker_ca_cert.subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(NOW)
        .not_valid_after(NOW + datetime.timedelta(days=365 * 5))
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(
            x509.SubjectKeyIdentifier.from_public_key(key.public_key()),
            critical=False,
        )
        .sign(broker_ca_key, hashes.SHA256())
    )
    _save_key(key_path, key)
    _save_cert(cert_path, cert)
    _ok(f"{org_id} org CA generated")
    return key, cert


def gen_agent_cert(
    agent_id: str,
    org_id: str,
    org_ca_key,
    org_ca_cert: x509.Certificate,
    trust_domain: str = "atn.local",
    key_type: str = "rsa",
) -> None:
    """Generate (or skip) the agent certificate with SPIFFE SAN URI."""
    org_dir = CERTS_DIR / org_id
    # '::' in the name is not valid as a filename — replace with '__'
    safe_name = agent_id.replace("::", "__")
    key_path = org_dir / f"{safe_name}-key.pem"
    cert_path = org_dir / f"{safe_name}.pem"

    if key_path.exists() and cert_path.exists():
        _skip(f"{agent_id} cert")
        return

    key = _gen_key(key_type, bits=2048)
    subject = _build_name(
        (NameOID.COMMON_NAME, agent_id),
        (NameOID.ORGANIZATION_NAME, org_id),
    )
    # SPIFFE ID: spiffe://trust-domain/org/agent-name
    _, agent_name = agent_id.split("::", 1)
    spiffe_id = f"spiffe://{trust_domain}/{org_id}/{agent_name}"

    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(org_ca_cert.subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(NOW)
        .not_valid_after(NOW + datetime.timedelta(days=365))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.SubjectKeyIdentifier.from_public_key(key.public_key()),
            critical=False,
        )
        .add_extension(
            x509.SubjectAlternativeName([
                x509.UniformResourceIdentifier(spiffe_id),
            ]),
            critical=False,
        )
        .sign(org_ca_key, hashes.SHA256())
    )
    _save_key(key_path, key)
    _save_cert(cert_path, cert)
    _ok(f"{agent_id} cert generated  (spiffe_id={spiffe_id})")


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the broker root CA.")
    parser.add_argument(
        "--key-type", choices=["rsa", "ec"], default="rsa",
        help="Broker CA key type: 'rsa' (RSA 4096, default) or 'ec' (ECDSA P-256).",
    )
    args = parser.parse_args()

    print("\n\033[1mAgent Trust Network — Broker Certificate Generation\033[0m\n")
    CERTS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\033[1m[1/1] Broker CA (key_type={args.key_type})\033[0m")
    gen_broker_ca(key_type=args.key_type)

    print(f"\n{GREEN}\033[1mBroker CA ready in {CERTS_DIR}{RESET}")
    print()
    print(f"  certs/broker-ca.pem")
    print(f"  certs/broker-ca-key.pem")
    print()
    print("Organizations generate their own certificates with join.py:")
    print("  python join.py --broker http://localhost:8000 \\")
    print("                 --org-id <org> --display-name <name> \\")
    print("                 --secret <secret> --agents <org>::<agent>")


if __name__ == "__main__":
    main()
