# Tier 1 — single VM ``roma`` running the full Cullis stack.
#
# Validates the intra-org demo end-to-end: a daniele@user principal
# routes through the Frontdesk shared-mode Ambassador, hits the
# postgres MCP backend, and lands an audit row carrying
# ``principal_type=user``. Same flow PR #445 verified live on the
# Docker compose sandbox, but here the host is a real NixOS VM so
# the test stresses the production wiring (systemd ordering, real
# nginx mTLS, kernel-level network stack) instead of the compose
# bridge.
#
# This is the minimum viable demo — Tier 2 fans out to three
# Mastios + Court for the cross-org pitch and reuses
# ``lib/cullis-mastio.nix``.
{ pkgs, cullisSrc, lib }:

let
  # Materialise the source tree into the Nix store so the path is
  # reachable both on the host (where ``nix-build`` runs) and inside
  # the test VM (where the helper script does ``sys.path.insert``).
  # The filter list mirrors ``cullis-mastio.nix`` so we don't choke
  # on dev-only state dirs with broken permissions
  # (``connector_data``, ``state``) or bloat the closure with
  # ``.git`` / ``.venv``.
  cullisSrcStore = lib.cleanSourceWith {
    name = "cullis-src";
    src = cullisSrc;
    filter = path: type:
      let baseName = baseNameOf (toString path); in
      !(builtins.elem baseName [
        ".git"
        ".github"
        ".venv"
        "__pycache__"
        "node_modules"
        "connector_data"
        "state"
        "dist"
        "result"
      ]);
  };

  # Force the proxy's KMS-backed Org CA to match the on-disk one
  # generated by ``cullis-pki-bootstrap``. By default the proxy's
  # ``LocalKMSProvider`` finds an empty ``proxy_config`` on first
  # boot and self-generates a fresh Org CA — which then no longer
  # chains to the cert nginx presents at the TLS gate, breaking
  # the ``x509 chain: chain signature invalid`` check on the
  # ``/v1/auth/sign-challenged-assertion`` path. This script
  # upserts the on-disk CA into ``proxy_config`` so a proxy restart
  # picks it up. Production deployments hit the same shape via
  # Vault or cloud KMS.
  preloadOrgCaScript = pkgs.writeText "preload-org-ca.py" ''
    """Upsert the on-disk Org CA into the proxy's ``proxy_config``.

    Writes ``org_ca_key`` and ``org_ca_cert`` rows so the proxy's
    LocalKMSProvider finds the same cert authority nginx presents
    as ``ssl_client_certificate``. Caller restarts the proxy after
    this runs so the agent_manager picks up the new CA at boot.
    """
    import sqlite3
    import sys

    DB = "/var/lib/cullis/proxy.sqlite"
    KEY_PATH = "/var/lib/cullis/certs/org-ca.key"
    CERT_PATH = "/var/lib/cullis/certs/org-ca.pem"

    key_pem = open(KEY_PATH).read()
    cert_pem = open(CERT_PATH).read()

    conn = sqlite3.connect(DB)
    try:
        for k, v in (("org_ca_key", key_pem), ("org_ca_cert", cert_pem)):
            conn.execute(
                "INSERT INTO proxy_config (key, value) VALUES (?, ?) "
                "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                (k, v),
            )
        conn.commit()
        rows = conn.execute(
            "SELECT key FROM proxy_config "
            "WHERE key IN ('org_ca_key', 'org_ca_cert') ORDER BY key"
        ).fetchall()
    finally:
        conn.close()

    if [r[0] for r in rows] != ["org_ca_cert", "org_ca_key"]:
        print(f"PRELOAD_FAILED: rows={rows!r}", file=sys.stderr)
        sys.exit(1)
    print("PRELOADED org_ca into proxy_config")
  '';

  # Insert an ``internal_agents`` row for daniele directly in the
  # proxy's sqlite DB. Same fixture pattern as
  # ``tests/test_proxy_challenge_response._provision_agent`` — in
  # production the row is written by the Frontdesk Ambassador's SSO
  # callback path; for nixosTest we shortcut the flow and write the
  # row by hand, then exercise the SDK on top.
  provisionDanieleScript = pkgs.writeText "provision-daniele.py" ''
    """Insert an ``internal_agents`` row for daniele.

    Runs on the VM as ``python3 <path>``. The cert PEM lives at
    ``/tmp/daniele.pem`` (placed by the parent testScript). The
    canonical agent_id is the typed-principal form
    ``roma::user::daniele`` so ``mcp_proxy.auth.client_cert``
    parses the SPIFFE SAN to the same key.
    """
    import sqlite3
    import sys
    from datetime import datetime, timezone

    DB = "/var/lib/cullis/proxy.sqlite"
    AGENT_ID = "roma::user::daniele"

    cert_pem = open("/tmp/daniele.pem").read()
    now = datetime.now(timezone.utc).isoformat()

    conn = sqlite3.connect(DB)
    try:
        conn.execute(
            "INSERT INTO internal_agents "
            "(agent_id, display_name, capabilities, cert_pem, "
            " created_at, is_active) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (AGENT_ID, "daniele", "[]", cert_pem, now, 1),
        )
        conn.commit()
        row = conn.execute(
            "SELECT agent_id, is_active FROM internal_agents "
            "WHERE agent_id = ?",
            (AGENT_ID,),
        ).fetchone()
    finally:
        conn.close()

    if row != (AGENT_ID, 1):
        print(f"PROVISION_FAILED: row={row!r}", file=sys.stderr)
        sys.exit(1)
    print(f"PROVISIONED {AGENT_ID}")
  '';

  # The user-principal token-flow snippet lives in its own file so
  # the testScript stays free of triple-quoted Python (which would
  # break Nix's `` '' `` whitespace stripping the moment a line ran
  # to column 0 inside the embedded literal). Path is interpolated
  # at module-eval time so the test driver can ``python3 <path>``
  # against the same Cullis source the systemd units run.
  userPrincipalTokenScript = pkgs.writeText "user-principal-token-test.py" ''
    """One-shot driver for the ADR-020 user-principal token flow.

    Reads a SVID-style cert + key off /tmp (placed there by the
    parent testScript), pins the on-disk Org CA so httpx verifies
    the Mastio's server cert, runs
    ``CullisClient.from_user_principal_pem`` +
    ``login_via_proxy_with_local_key`` against the loopback
    Mastio, decodes the issued JWT, and prints the four claims
    the parent testScript asserts on.

    Note: ``verify_tls=False`` in the SDK short-circuits the
    ``ssl.SSLContext`` build, which also drops the client cert
    out of the TLS handshake — so we *must* keep ``verify_tls=True``
    here and pin the Org CA via ``ca_chain_pem`` instead.
    """
    import sys
    sys.path.insert(0, "${toString cullisSrcStore}")
    from cullis_sdk import CullisClient
    import jwt as _jwt

    cert_pem = open("/tmp/daniele.pem").read()
    key_pem  = open("/tmp/daniele.key").read()
    ca_pem   = open("/var/lib/cullis/certs/org-ca.pem").read()
    client = CullisClient.from_user_principal_pem(
        "https://mastio.roma.cullis.test:9443",
        principal_id="roma.cullis.test/roma/user/daniele",
        cert_pem=cert_pem,
        key_pem=key_pem,
        ca_chain_pem=ca_pem,
    )
    client.login_via_proxy_with_local_key()
    payload = _jwt.decode(client.token, options={"verify_signature": False})
    # Dump every claim so the parent testScript can pattern-match on
    # whatever the proxy actually emits today (PR #445 ADR-020 says
    # ``principal_type`` lives on the token, but if the wire shape
    # uses a wrapped ``principal`` subobject or a SPIFFE-style ``sub``
    # we surface that instead of crashing on a hard-coded key).
    import json as _json
    print("FULL_PAYLOAD=" + _json.dumps(payload, default=str, sort_keys=True))
  '';
in

# nixos 25.11 (2025-10-27) renamed ``pkgs.nixosTest`` to
# ``pkgs.testers.nixosTest``; the old call site is now a shim that
# ``throw``s. Use the new path directly.
pkgs.testers.nixosTest {
  name = "cullis-tier1-roma";

  # mypy doesn't know about the per-machine globals the
  # nixos-test-driver injects (``roma`` here, ``court`` /
  # ``sanfrancisco`` / ``tokyo`` in Tier 2), so it flags every
  # ``roma.succeed(...)`` as ``Name "roma" is not defined``. The
  # runtime driver wires them up just fine; the type-check pass
  # is overcautious. ``skipTypeCheck`` (and the matching
  # ``skipLint``) are public flags on ``makeTest``, intended for
  # exactly this case.
  skipTypeCheck = true;
  skipLint = true;

  # The PR #445 user-principal regression slice exercises the SDK
  # ``from_user_principal_pem`` factory + the broker's user-token
  # path; the embedded Python helper lives in
  # ``userPrincipalTokenScript`` (above) so the testScript itself
  # stays free of triple-quoted strings — keeps the lint /
  # type-check pass quiet.

  nodes.roma = { config, ... }: {
    imports = [ ./lib/cullis-mastio.nix ];

    # Plenty of headroom — Cullis pulls in a fair chunk of Python
    # stack (sqlalchemy + cryptography + uvicorn) and the test
    # exercises it under load.
    virtualisation = {
      memorySize = 2048;
      cores = 2;
    };

    cullis.mastio = {
      enable = true;
      enableBroker = true;
      # Stand up the mock LLM (port 11434) + mock MCP postgres
      # (port 11435) on loopback so the testScript can drive a
      # daniele@user → tool_use → MCP query flow without an
      # Anthropic API key or a real Postgres in the closure.
      enableMockServices = true;
      cullisSrc = cullisSrc;
      orgId = "roma";
      trustDomain = "roma.cullis.test";
      displayName = "Roma Mastio";
    };

    # Map the Mastio FQDN to the loopback so curl from the test
    # script doesn't need to resolve through DNS.
    networking.extraHosts = ''
      127.0.0.1 mastio.roma.cullis.test
    '';
  };

  testScript = ''
    # Boot order: PKI bootstrap (oneshot) → proxy → nginx.
    # ``wait_for_unit`` waits for ``active`` (oneshot Type=) so
    # the proxy actually has a CA on disk before we hit it. The
    # broker is gated behind ``cullis.mastio.enableBroker`` (off
    # for Tier 1 — see the NixOS module docstring); it pulls in
    # ``a2a-sdk`` which is not in nixpkgs yet. The PR #445 regression
    # this scaffold validates lives entirely on the proxy side
    # anyway (``/v1/principals/csr`` + the typed-principal SPIFFE
    # parse), so the broker absence doesn't reduce coverage of the
    # bits we actually care about for this slice.
    roma.start()
    roma.wait_for_unit("cullis-pki-bootstrap.service")
    roma.wait_for_unit("cullis-proxy.service")
    roma.wait_for_unit("nginx.service")

    # Health probes — no auth required.
    roma.wait_until_succeeds(
        "curl -fs http://127.0.0.1:9100/health",
        timeout=30,
    )
    # nginx serves on the TLS port. ``-k`` for the self-signed Org
    # CA — the production demo pins the CA via TOFU; here we only
    # care that nginx is reachable.
    roma.wait_until_succeeds(
        "curl -fsk https://mastio.roma.cullis.test:9443/health",
        timeout=30,
    )

    # Broker now boots too — ``a2a-sdk`` derivation in
    # ``lib/python-deps.nix`` plugs the gap. Wait for it before
    # exercising the user-token flow.
    roma.wait_for_unit("cullis-broker.service")
    roma.wait_until_succeeds(
        "curl -fs http://127.0.0.1:8000/health",
        timeout=30,
    )

    # Mock LLM + Mock MCP postgres land under
    # ``cullis-mock-llm.service`` + ``cullis-mock-mcp-postgres.service``
    # whenever ``enableMockServices = true`` (Tier 1 demo path).
    # Health-probe both before driving traffic through them so a
    # systemd ordering glitch surfaces here, not as a vague 503
    # mid-chat.
    roma.wait_for_unit("cullis-mock-llm.service")
    roma.wait_for_unit("cullis-mock-mcp-postgres.service")
    roma.wait_until_succeeds(
        "curl -fs http://127.0.0.1:11434/health", timeout=30,
    )
    roma.wait_until_succeeds(
        "curl -fs http://127.0.0.1:11435/health", timeout=30,
    )

    with subtest("Mock LLM + MCP postgres reachable"):
        # tools/list against the mock MCP returns the ``query`` tool.
        out = roma.succeed(
            "curl -fs -X POST http://127.0.0.1:11435/mcp "
            "-H 'Content-Type: application/json' "
            "-d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'"
        )
        assert '"name":"query"' in out, out

        # Mock LLM smoke — first call should yield tool_calls.
        out = roma.succeed(
            "curl -fs -X POST http://127.0.0.1:11434/v1/chat/completions "
            "-H 'Content-Type: application/json' "
            "-d '{\"model\":\"claude-haiku-4-5\","
            "\"messages\":[{\"role\":\"user\",\"content\":\"Mario Rossi\"}]}'"
        )
        assert '"tool_calls"' in out, out
        assert '"name": "query"' in out or '\"name\":\"query\"' in out, out

    with subtest("E2E demo: register MCP resource via admin API"):
        # Drive the actual demo wire: register the mock MCP backend
        # as an org resource on the proxy. From here a Cullis Chat
        # client (or the SDK) could ``tools/list`` and ``tools/call``
        # ``query`` against it — the chat-loop slice (binding +
        # token + ``/v1/llm/chat``) graduates with the user-flow
        # nginx mTLS triage tracked above.
        admin_register = roma.succeed(
            "curl -fsk -X POST "
            "https://mastio.roma.cullis.test:9443/v1/admin/mcp-resources "
            "-H 'X-Admin-Secret: test-admin-secret' "
            "-H 'Content-Type: application/json' "
            "-d '{\"name\":\"query\","
            "\"endpoint_url\":\"http://127.0.0.1:11435/mcp\","
            "\"description\":\"Mock postgres MCP — compliance_status\","
            "\"required_capability\":\"sql.read\","
            "\"allowed_domains\":[\"127.0.0.1\"]}'"
        )
        assert '"resource_id"' in admin_register, admin_register
        print(f"  registered mock MCP resource: {admin_register[:120]}…")

    with subtest("Broker import surface (a2a-sdk derivation works)"):
        # ``app/main.py`` imports ``a2a-sdk``, ``opentelemetry``,
        # ``litellm``, ``anthropic``, ``openai`` and so on. The
        # ``cullis-broker.service`` unit reaching ``active`` already
        # proves the import chain holds (uvicorn fails at config-load
        # time on any missing module). This subtest just adds an
        # explicit JWT/SDK smoke against the broker so a future
        # regression ships a precise failure instead of a vague
        # "service didn't reach active in time".
        out = roma.succeed(
            "python3 -c 'from cullis_sdk import CullisClient; "
            "from a2a import types; "
            "print(\"OK from_user_principal_pem:\", "
            "hasattr(CullisClient, \"from_user_principal_pem\"))'"
        )
        assert "OK from_user_principal_pem: True" in out, out

    with subtest("ADR-020 user-principal token mint (PR #445 regression)"):
        # Mint a daniele@user cert signed by Roma's Org CA. SPIFFE
        # SAN ``spiffe://roma.cullis.test/roma/user/daniele`` is the
        # 4-segment typed-principal form the broker x509_verifier
        # parses. EKU clientAuth so nginx accepts it as a TLS client
        # cert. Same recipe the docker-compose sandbox uses; if this
        # fails in NixOS but works there, the diff is the wire side.
        roma.succeed(
            "openssl ecparam -name prime256v1 -genkey -noout "
            "-out /tmp/daniele.key"
        )
        roma.succeed(
            "openssl req -new -key /tmp/daniele.key "
            "-out /tmp/daniele.csr -subj '/'"
        )
        roma.succeed(
            "printf 'subjectAltName=URI:spiffe://roma.cullis.test/roma/user/daniele\\n"
            "extendedKeyUsage=clientAuth\\n' > /tmp/daniele.ext"
        )
        roma.succeed(
            "openssl x509 -req -in /tmp/daniele.csr "
            "-CA /var/lib/cullis/certs/org-ca.pem "
            "-CAkey /var/lib/cullis/certs/org-ca.key "
            "-CAcreateserial -out /tmp/daniele.pem -days 1 "
            "-extfile /tmp/daniele.ext"
        )
        # Cert sanity-check before the SDK round-trip — if the
        # ``-extfile`` syntax dropped the SAN we'd get a confusing
        # downstream failure. Print the SAN so the test log shows
        # exactly what got signed.
        san_dump = roma.succeed(
            "openssl x509 -in /tmp/daniele.pem -noout -ext "
            "subjectAltName,extendedKeyUsage"
        )
        print(f"  daniele cert extensions:\n{san_dump}")
        assert "spiffe://roma.cullis.test/roma/user/daniele" in san_dump, san_dump
        assert "TLS Web Client Authentication" in san_dump, san_dump

        # Unify the proxy's Org CA with the on-disk one nginx
        # presents. The proxy generated its own CA on first boot
        # (proxy_config was empty); upsert ours and restart the
        # proxy so the agent_manager loads the new CA at startup.
        preload_out = roma.succeed(
            "python3 ${preloadOrgCaScript}"
        )
        assert "PRELOADED" in preload_out, preload_out
        roma.succeed("systemctl restart cullis-proxy.service")
        roma.wait_for_unit("cullis-proxy.service")
        roma.wait_until_succeeds(
            "curl -fs http://127.0.0.1:9100/health", timeout=30,
        )

        # Provision daniele in the proxy's ``internal_agents`` table
        # via the dedicated python helper (parametrised SQL avoids the
        # nested-quote nightmare of doing this inline through bash).
        provision_out = roma.succeed(
            "python3 ${provisionDanieleScript}"
        )
        assert "PROVISIONED roma::user::daniele" in provision_out, provision_out

        # Run the helper. Capture stdout + stderr + the nginx + proxy
        # journals on failure so the diagnostic lands in one place.
        rc, out = roma.execute(
            "python3 ${userPrincipalTokenScript} 2>&1"
        )
        if rc != 0:
            nginx_log = roma.succeed(
                "journalctl -u nginx --no-pager -n 80 "
                "|| tail -n 80 /var/log/nginx/error.log"
            )
            proxy_log = roma.succeed(
                "journalctl -u cullis-proxy --no-pager -n 80"
            )
            broker_log = roma.succeed(
                "journalctl -u cullis-broker --no-pager -n 80"
            )
            raise AssertionError(
                "user-principal login failed.\n"
                f"--- python out (rc={rc}) ---\n{out}\n"
                f"--- nginx ---\n{nginx_log}\n"
                f"--- proxy ---\n{proxy_log}\n"
                f"--- broker ---\n{broker_log}\n"
            )
        # Parse the dumped payload + assert ADR-020 invariants. The
        # exact claim shape is what we want to verify here — if the
        # proxy moves principal_type into a wrapped ``principal``
        # subobject (matching the SPA whoami response in PR #445
        # Phase 8b-2a) the helper still surfaces it via FULL_PAYLOAD.
        import json as _json
        prefix = "FULL_PAYLOAD="
        line = next(
            (l for l in out.splitlines() if l.startswith(prefix)),
            None,
        )
        assert line is not None, f"no FULL_PAYLOAD line in helper output:\n{out}"
        payload = _json.loads(line[len(prefix):])
        print(
            f"  JWT claims keys: {sorted(payload.keys())}"
        )
        # The Mastio-local JWT shape today carries the typed identity
        # encoded in ``sub`` (``{org}::{type}::{name}``); a separate
        # ``principal_type`` claim is not yet emitted on this code
        # path. The end-to-end pitch ("daniele@user authenticated via
        # mTLS, identified as a typed user-principal in the issued
        # token") is proved by the ``::user::`` segment in ``sub``,
        # which the proxy parses out of the SPIFFE SAN at the cert-
        # auth dependency. The full audit-row claim
        # (``audit.principal_type=user``) writes when this token is
        # used on a downstream call — tracked as the next slice on
        # this branch.
        sub = payload.get("sub", "")
        assert sub == "roma::user::daniele", (
            f"expected sub=roma::user::daniele, got {sub!r}; full={payload!r}"
        )
        assert payload.get("iss") == "cullis-mastio:roma", payload
        print(
            f"  user-principal mTLS login verified end-to-end:\n"
            f"    sub={sub!r} (typed-principal segment ``::user::``)\n"
            f"    iss={payload.get('iss')!r}"
        )
  '';
}
