"""add client_seq to session_messages

Revision ID: 3ee228696375
Revises: 473ecda4a4ca
Create Date: 2026-04-04 17:15:40.433596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee228696375'
down_revision: Union[str, Sequence[str], None] = '473ecda4a4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_messages', sa.Column('client_seq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_messages', 'client_seq')
    # ### end Alembic commands ###
