"""initial schema

Revision ID: 473ecda4a4ca
Revises: 
Create Date: 2026-04-04 16:42:23.465083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473ecda4a4ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=256), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('secret_hash', sa.String(length=256), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cert_pem', sa.Text(), nullable=True),
    sa.Column('cert_thumbprint', sa.String(length=64), nullable=True),
    sa.Column('token_invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agents_org_id'), 'agents', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('org_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_agent_id'), 'audit_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_log_session_id'), 'audit_log', ['session_id'], unique=False)
    op.create_table('bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('scope_json', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'agent_id', name='uq_binding_org_agent')
    )
    op.create_index(op.f('ix_bindings_agent_id'), 'bindings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bindings_org_id'), 'bindings', ['org_id'], unique=False)
    op.create_table('jti_blacklist',
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('recipient_type', sa.String(length=16), nullable=False),
    sa.Column('recipient_id', sa.String(length=256), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=True),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(length=256), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_acted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_type'), 'notifications', ['recipient_type'], unique=False)
    op.create_table('organizations',
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('secret_hash', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ca_certificate', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(length=128), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('policy_type', sa.String(length=32), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_policies_policy_id'), 'policies', ['policy_id'], unique=True)
    op.create_table('revoked_certs',
    sa.Column('serial_hex', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_by', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('cert_not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('serial_hex')
    )
    op.create_index(op.f('ix_revoked_certs_agent_id'), 'revoked_certs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_revoked_certs_org_id'), 'revoked_certs', ['org_id'], unique=False)
    op.create_table('session_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('sender_agent_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_session_seq')
    )
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('initiator_agent_id', sa.String(length=128), nullable=False),
    sa.Column('initiator_org_id', sa.String(length=128), nullable=False),
    sa.Column('target_agent_id', sa.String(length=128), nullable=False),
    sa.Column('target_org_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_capabilities', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index(op.f('ix_revoked_certs_org_id'), table_name='revoked_certs')
    op.drop_index(op.f('ix_revoked_certs_agent_id'), table_name='revoked_certs')
    op.drop_table('revoked_certs')
    op.drop_index(op.f('ix_policies_policy_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_recipient_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('jti_blacklist')
    op.drop_index(op.f('ix_bindings_org_id'), table_name='bindings')
    op.drop_index(op.f('ix_bindings_agent_id'), table_name='bindings')
    op.drop_table('bindings')
    op.drop_index(op.f('ix_audit_log_session_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_agent_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agents_org_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
