"""add oidc columns to organizations

Revision ID: 7043c1ddb652
Revises: 7f54c1eb5e89
Create Date: 2026-04-04 17:55:37.785309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7043c1ddb652'
down_revision: Union[str, Sequence[str], None] = '7f54c1eb5e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('oidc_issuer_url', sa.String(length=512), nullable=True))
    op.add_column('organizations', sa.Column('oidc_client_id', sa.String(length=256), nullable=True))
    op.add_column('organizations', sa.Column('oidc_client_secret', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'oidc_client_secret')
    op.drop_column('organizations', 'oidc_client_id')
    op.drop_column('organizations', 'oidc_issuer_url')
    # ### end Alembic commands ###
