"""``pki_key_store`` + ``legacy_pki_archive`` — encrypted PKI key storage.

Revision ID: 0038_pki_key_store
Revises: 0037_audit_dev_attest
Create Date: 2026-05-18 09:00:00.000000

Three-tier PKI hardening (issue #261, audit 2026-05-18). Pre-fix:

* Org Root CA private key sat as plaintext PEM in ``proxy_config.org_ca_key``
  (routed via the KMS provider, but the LocalKMSProvider default just writes
  ``proxy_config`` as text).
* Mastio Intermediate CA private key sat as plaintext PEM in
  ``proxy_config.mastio_ca_key`` (no KMS provider involvement at all).
* Agent leaf certs were issued by the Org Root directly, so the Intermediate
  CA carried no real operational load.

This migration adds two tables that close the gap:

1. ``pki_key_store`` (key_id TEXT PK, key_type TEXT, ciphertext TEXT,
   cert_pem TEXT, created_at TEXT, activated_at TEXT, deprecated_at TEXT,
   expires_at TEXT) — the new home for cold-storage Org Root + active
   Mastio Intermediate keypairs. ``ciphertext`` is the Fernet envelope
   produced by :mod:`mcp_proxy.tools.secret_encrypt`, so a DB-only leak
   surrenders no usable key material without the master key (env var
   ``MCP_PROXY_DB_ENCRYPTION_KEY`` aliased to the existing
   ``MCP_PROXY_SECRET_ENCRYPTION_KEY_B64``).

2. ``legacy_pki_archive`` (key_id TEXT PK, key_type TEXT, legacy_pem TEXT,
   archived_at TEXT) — Phase 0 wipe target. On first boot post-fix, the
   plaintext ``proxy_config.org_ca_key`` and ``proxy_config.mastio_ca_key``
   rows are copied here (audit trail + worst-case rollback hatch) before
   being deleted from ``proxy_config``. Reissue proceeds from a clean
   slate with the new schema. Hard migration — the user confirmed no
   live deploys exist, so there's no backward compatibility surface.

Both tables are schema-only here. The Phase 0 wipe data migration runs
at proxy boot in ``AgentManager`` rather than Alembic (PEM parsing +
key derivation pull in the ``cryptography`` dep, which the standalone
``proxy-init`` container does not carry — same reasoning as 0018).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "0038_pki_key_store"
down_revision: Union[str, Sequence[str], None] = "0037_audit_dev_attest"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "pki_key_store" not in existing_tables:
        op.create_table(
            "pki_key_store",
            # ``key_id`` is opaque, generated by AgentManager. For the
            # cold Org Root it is the SHA-256 thumbprint of the pubkey
            # DER (first 16 hex chars), matching ``derive_org_id_from_ca``.
            # For Intermediate CAs it is ``"intermediate-" + same hash``.
            sa.Column("key_id", sa.Text(), primary_key=True),
            # ``org_ca`` | ``intermediate_ca``. Mastio Leaf stays in the
            # existing ``mastio_keys`` table (it already has the rotation
            # state machine ADR-012 Phase 2.1 hardened around it).
            sa.Column("key_type", sa.Text(), nullable=False),
            # Fernet envelope from mcp_proxy.tools.secret_encrypt. JSON
            # payload {"key_pem": "...", "cert_pem": "..."} — bundled so
            # a single decrypt round-trips both halves of the keypair.
            sa.Column("ciphertext", sa.Text(), nullable=False),
            # Public cert PEM held in clear (it is public material) so
            # callers that only need verification (CA bundle endpoint,
            # subject CN sanity check) don't need to touch the master
            # key. Always populated; the migration enforces NOT NULL.
            sa.Column("cert_pem", sa.Text(), nullable=False),
            sa.Column("created_at", sa.Text(), nullable=False),
            sa.Column("activated_at", sa.Text(), nullable=True),
            sa.Column("deprecated_at", sa.Text(), nullable=True),
            sa.Column("expires_at", sa.Text(), nullable=True),
        )
        op.create_index(
            "idx_pki_key_store_type_active",
            "pki_key_store",
            ["key_type", "activated_at", "deprecated_at"],
        )

    if "legacy_pki_archive" not in existing_tables:
        op.create_table(
            "legacy_pki_archive",
            sa.Column("key_id", sa.Text(), primary_key=True),
            sa.Column("key_type", sa.Text(), nullable=False),
            # legacy_pem is the unencrypted PEM as it was in proxy_config
            # pre-wipe. Operators who keep this DB column around accept
            # the same risk surface they had pre-migration; the Phase 0
            # wipe runs once and leaves an audit row in audit_log so the
            # archived material is discoverable.
            sa.Column("legacy_pem", sa.Text(), nullable=False),
            sa.Column("archived_at", sa.Text(), nullable=False),
        )


def downgrade() -> None:
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())
    if "pki_key_store" in existing:
        op.drop_index("idx_pki_key_store_type_active", table_name="pki_key_store")
        op.drop_table("pki_key_store")
    if "legacy_pki_archive" in existing:
        op.drop_table("legacy_pki_archive")
