"""Wave B B1 (audit 2026-05-11) — at-rest encryption for sensitive
columns on the Mastio.

Pre-fix the AI provider credentials lived as plaintext JSON in
``ai_provider_credentials.creds_json``. A read on the SQLite file or
a Postgres backup leak surrendered every upstream LLM API key
(Anthropic, OpenAI, AWS Bedrock, GCP service-account JSON, Gemini)
in cleartext.

This module provides a Fernet-based envelope so callers can write
``creds_json`` as ``enc:v1:<token>`` instead. The master key is
process-derived from ``settings.secret_encryption_key_b64`` (env or
``proxy_config`` row, autogenerated on first boot).

Forward-compat:
  - ``enc:v1:`` → Fernet (current).
  - Plaintext (no prefix) → returned unchanged on read (legacy /
    migration-pending rows; the 0032 migration upgrades them).

The KMS layer (``mcp_proxy/kms/``) wraps the Org CA keypair —
out of scope here. A future enterprise provider can subclass
``SecretEncryptor`` to back the master key with AWS KMS / GCP KMS /
Azure KV, but the sqlite envelope stays the same.
"""
from __future__ import annotations

import base64
import logging
import os
import secrets

from cryptography.fernet import Fernet, InvalidToken

_log = logging.getLogger("mcp_proxy.tools.secret_encrypt")

_PREFIX = "enc:v1:"
_PROXY_CONFIG_KEY = "secret_encryption_key_b64"


_master_key: bytes | None = None


def _bytes_to_fernet_key(raw: bytes) -> bytes:
    """Fernet expects 32 raw bytes encoded as urlsafe-base64. Accept
    either the raw 32-byte material or the already-base64 form."""
    if len(raw) == 32:
        return base64.urlsafe_b64encode(raw)
    if len(raw) == 44:
        # Already base64-encoded form; validate by decoding.
        try:
            decoded = base64.urlsafe_b64decode(raw)
            if len(decoded) == 32:
                return raw
        except Exception:
            pass
    raise ValueError(
        f"secret_encryption_key must be 32 raw bytes (got {len(raw)})"
    )


async def _load_or_create_master_key() -> bytes:
    """Resolve the Fernet master key.

    Order of precedence:
      1. ``MCP_PROXY_SECRET_ENCRYPTION_KEY_B64`` env (cluster operator
         pinned the value, e.g. via Vault Helm secret store).
      2. ``proxy_config`` row ``secret_encryption_key_b64`` (persisted
         per-install random — same row across restarts, so encrypted
         data round-trips).
      3. Cold-install: generate ``secrets.token_bytes(32)``, persist
         to step 2's row, return.

    Returns the urlsafe-base64 form Fernet expects.
    """
    global _master_key
    if _master_key is not None:
        return _master_key

    env_val = os.environ.get("MCP_PROXY_SECRET_ENCRYPTION_KEY_B64", "").strip()
    if env_val:
        try:
            raw = base64.urlsafe_b64decode(env_val)
        except Exception as exc:
            raise RuntimeError(
                "MCP_PROXY_SECRET_ENCRYPTION_KEY_B64 is not valid "
                "urlsafe-base64"
            ) from exc
        _master_key = _bytes_to_fernet_key(raw)
        return _master_key

    # DB-backed fallback. Lazy import to avoid a dep cycle:
    # ``mcp_proxy.db`` imports this module from upsert/get helpers.
    from mcp_proxy.db import get_config, set_config

    stored = await get_config(_PROXY_CONFIG_KEY)
    if stored:
        try:
            raw = base64.urlsafe_b64decode(stored)
        except Exception as exc:
            raise RuntimeError(
                f"{_PROXY_CONFIG_KEY} in proxy_config is not "
                "valid urlsafe-base64"
            ) from exc
        _master_key = _bytes_to_fernet_key(raw)
        return _master_key

    # Cold install — mint + persist.
    raw = secrets.token_bytes(32)
    encoded = base64.urlsafe_b64encode(raw).decode()
    await set_config(_PROXY_CONFIG_KEY, encoded)
    _log.warning(
        "secret_encryption_key minted on first boot and persisted to "
        "proxy_config. Override via env "
        "MCP_PROXY_SECRET_ENCRYPTION_KEY_B64 to manage out-of-band."
    )
    _master_key = _bytes_to_fernet_key(raw)
    return _master_key


async def encrypt_at_rest(plaintext: str) -> str:
    """Wrap ``plaintext`` in the v1 Fernet envelope.

    Empty / None passthrough — caller decides whether to store NULL
    vs an empty encrypted blob. We avoid encrypting an empty string
    so a NULL ``creds_json`` round-trips as NULL, not as an envelope
    of "".
    """
    if plaintext is None or plaintext == "":
        return plaintext
    key = await _load_or_create_master_key()
    token = Fernet(key).encrypt(plaintext.encode("utf-8")).decode("utf-8")
    return _PREFIX + token


async def decrypt_at_rest(blob: str | None) -> str | None:
    """Reverse of :func:`encrypt_at_rest`.

    Legacy / migration-pending rows stored as plaintext (no
    ``enc:v1:`` prefix) are returned as-is so the rest of the code
    can read them while the 0032 migration is still rolling out.
    Once a row has been encrypted via this module, attempts to
    decrypt with the wrong master key raise ``InvalidToken`` —
    caller should treat that as "credential lost", not as plaintext
    fallback.
    """
    if blob is None or blob == "":
        return blob
    if not blob.startswith(_PREFIX):
        # Legacy / pre-migration row — return as-is.
        return blob
    key = await _load_or_create_master_key()
    token = blob[len(_PREFIX):]
    try:
        return Fernet(key).decrypt(token.encode("utf-8")).decode("utf-8")
    except InvalidToken as exc:
        # Wrong key (operator rotated MCP_PROXY_SECRET_ENCRYPTION_KEY_B64
        # without re-encrypting rows). Fail loudly — falling back to
        # the ciphertext as plaintext would be a worse failure mode.
        raise RuntimeError(
            "secret_encryption_key cannot decrypt the stored row — "
            "either the key was rotated without re-encryption, or the "
            "row was encrypted by a different deploy"
        ) from exc


def _reset_master_key_for_tests() -> None:
    """Test hook: forget the cached master key so the next call
    re-resolves from env / DB."""
    global _master_key
    _master_key = None
