name: DCO

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  dco-check:
    name: Signed-off-by check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR commits
        id: get-pr-commits
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check DCO
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
